---
# input path modules (location of cloned scripts in local computer)
dir_source   : /home/rpg002/Diagnostics/cccma_boostENS/CCCma_boostENS_JGRMLComp/figures_paper

# output path 
dir_frnt_out : /space/hall5/sitestore/eccc/crd/ccrn/users/rpg002/DCPP_Diagnostics/BoostEnsemblev2obs


define: &dir_hist_data  '/space/hall5/sitestore/eccc/crd/ccrn/users/rpg002/data/tas/observations'
# define: &dir_hist_VAE4  '/space/hall5/sitestore/eccc/crd/ccrn/users/rpg002/output/tas/SOM-FFN/results/Autoencoder/run_set_final_historical/ST2010_v2_VAL5_Banealing_L0_archNone_batch100_e100_cosine_lr_scheduler_cEBVAE_50-100_historical_TSE10_LS500_condembsize5_EQW_YES/tests'
# define: &dir_hist_benchmark  '/space/hall5/sitestore/eccc/crd/ccrn/users/rpg002/output/tas/SOM-FFN/results/Autoencoder/run_set_final_historical/ST2010_v2_VAL5_Banealing_L0_archNone_batch100_e100_cosine_lr_scheduler_cEBVAE_50-100_historical_TSE10_LS500_condembsize5_EQW_YES/tests'

define: &dir_hist_VAE1  '/space/hall5/sitestore/eccc/crd/ccrn/users/rpg002/output/tas/SOM-FFN/results/Autoencoder/run_set_final_obs_long/ST2025_v2.1_VAL5_Banealing_L0_archNone_batch100_e100_cosine_lr_scheduler_cEBVAE_50-100_historical_TSE1_LS500_condembsize2_EQW/tests'
# define: &dir_hist_VAE2  '/space/hall5/sitestore/eccc/crd/ccrn/users/rpg002/output/tas/SOM-FFN/results/Autoencoder/run_set_final_historical_long/ST2026_v2.1_VAL5_Banealing_L0_archNone_batch100_e200_cosine_lr_scheduler_cEBVAE_50-100_historical_TSE1_LS500_condembsize2_EQW/tests'
# define: &dir_hist_VAE3  '/space/hall5/sitestore/eccc/crd/ccrn/users/rpg002/output/tas/SOM-FFN/results/Autoencoder/run_set_final_historical_long/ST2026_v2.1_VAL5_Banealing_L0_archNone_batch100_e200_cosine_lr_scheduler_cEBVAE_50-100_historical_TSE1_LS500_condembsize2_EQW/tests'
# 

# input files (historical dataset)
define: &file_hist_population  'tas_era5_194001_202412_128_64' 
define: &file_hist_VAE1  '*_saved_model_normal_based_on_train_sampling2_1stds_output_sampling_multinormal_based_on_train_sampling'
# define: &file_hist_VAE3  '*_saved_model_normal_based_on_train_sampling2_1stds_output_sampling_None'
# define: &file_hist_VAE4  '*_saved_model_1stds_output_sampling_None'
# define: &file_hist_benchmark  '*_saved_model_use_condition_output_sampling_multinormal_based_on_train_sampling'
# define: &file_hist_VAE1  '*_saved_model_1stds_output_sampling_multinormal_based_on_train_sampling'

####################
# input basic info #
####################

variable:    # variables (choose one -or the first one is read in)
- tas

list_data_raw:
- population
- train_sample


list_data_hist:
# - hist_VAE1
- hist_VAE1
# - hist_VAE3
# - hist_benchmark




# climate data dictionary
data_hist_info :
 population :
   dir_in  : *dir_hist_data
   file_in : *file_hist_population
   var_in  : tas
   unit_change  : 1


 hist_VAE1:
   dir_in  : *dir_hist_VAE1
   file_in : *file_hist_VAE1
   var_in  : nn_adjusted
   unit_change  : 1

#  hist_VAE2:
#    dir_in  : *dir_hist_VAE2
#    file_in : *file_hist_VAE2
#    var_in  : nn_adjusted
#    unit_change  : 1

#  hist_VAE3:
#    dir_in  : *dir_hist_VAE3
#    file_in : *file_hist_VAE3
#    var_in  : nn_adjusted
#    unit_change  : 1

#  hist_VAE4:
#    dir_in  : *dir_hist_VAE4
#    file_in : *file_hist_VAE4
#    var_in  : nn_adjusted
#    unit_change  : 1

#  hist_benchmark:
#    dir_in  : *dir_hist_benchmark
#    file_in : *file_hist_benchmark
#    var_in  : nn_adjusted
#    unit_change  : 1






        
dict_seasons :
  DJF : [12,1,2]
  JJA : [6,7,8] 
  D : [12]  
  A : [8] 
  Full : [1,2,3,4,5,6,7,8,9,10,11,12]       
        



